import { createHash } from "node:crypto";
import type { BenchmarkResultLedger } from "../benchmark-result-ledger.js";
import { validateFacts } from "../facts-contract.js";
import type { ResearchDecisionCard } from "../research-decision-card.js";
import type { CompanyProfile, EventRecord, ResearchRecord } from "../types.js";
import type { ExplainerSource } from "./contracts.js";
const hash=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex"); const eid=(u:string)=>`evidence:${hash(u).slice(0,16)}`;
export function buildExplainerSources(input:{events:EventRecord[];companies:CompanyProfile[];researchRecords:ResearchRecord[];researchDecisionCards:ResearchDecisionCard[];benchmarkResultLedger:BenchmarkResultLedger}):ExplainerSource[]{
 const companies=new Map(input.companies.map(c=>[c.name,c]));
 const events=input.events.flatMap((e):ExplainerSource[]=>{const owner=e.primaryEntity&&companies.get(e.primaryEntity);const v=validateFacts({...e,public:true,eventDate:e.occurredAt??e.eventDate,publishedAt:e.lastEvidenceAt,materiallyChangedAt:e.lastMaterialChangeAt,evidence:e.evidence.map(x=>({link:x.link,source:x.source,grade:x.grade,publishedAt:x.publishedAt}))});if(!owner||!v.valid||!v.publicEligible||!e.facts.length)return[];const evidence=e.evidence.filter(x=>v.qualifyingEvidenceIds.includes(x.link)).map(x=>({evidenceId:eid(x.link),url:x.link,source:x.source}));if(!evidence.length)return[];const facts=e.facts.map((text,i)=>({factId:`${e.id}:fact:${i+1}`,text,evidenceIds:evidence.map(x=>x.evidenceId)}));const base={canonicalId:`event:${e.id}`,kind:"event" as const,entityNames:[owner.name],eventDate:v.times.eventDate,publishedAt:v.times.publishedAt,materiallyChangedAt:v.times.materiallyChangedAt,facts,evidence,contexts:e.routes};return[{...base,revision:hash(base)}]});
 const cards=new Map(input.researchDecisionCards.map(c=>[c.identity.paperId.value,c]));const ledgers=new Map(input.benchmarkResultLedger.entries.filter(e=>!e.gateCodes.length).map(e=>[e.paperId,e]));
 const research=input.researchRecords.flatMap((r):ExplainerSource[]=>{const c=cards.get(r.id);if(!c||r.status==="已撤稿"||r.article.scholar?.isRetracted||c.gates.length||c.factsZh.value==="unknown")return[];const evidence=[...new Set(c.factsZh.evidenceUrls)].map(url=>({evidenceId:eid(url),url,source:r.article.source}));if(!evidence.length)return[];const facts=c.factsZh.value.map((text,i)=>({factId:`${r.id}:fact:${i+1}`,text,evidenceIds:evidence.map(x=>x.evidenceId)}));const l=ledgers.get(r.id);const comparable=l&&l.fields.baseline.value!=="unknown"&&l.fields.result.value!=="unknown"&&l.fields.metric.value!=="unknown"?{before:String(l.fields.baseline.value),after:String(l.fields.result.value),task:String(l.fields.metric.value),conditions:l.benchmarkKey,evidenceIds:evidence.map(x=>x.evidenceId)}:undefined;const publishedAt=Number.isFinite(r.article.publishedAt.getTime())?r.article.publishedAt.toISOString():"unknown";const base={canonicalId:`research:${r.id}`,kind:"research" as const,entityNames:c.lab.value==="unknown"?[]:c.lab.value,eventDate:publishedAt,publishedAt,materiallyChangedAt:r.changes.at(-1)?.date??publishedAt,facts,evidence,contexts:c.task.value==="unknown"?[]:c.task.value,...(comparable?{comparable}:{})};return[{...base,revision:hash(base)}]});return[...events,...research].sort((a,b)=>a.canonicalId.localeCompare(b.canonicalId));
}
