import { createHash } from "node:crypto";
import type { ExplainerModel, ExplainerRunReport, ExplainerSource, ProgressExplainerCard, ProgressExplainersArtifact } from "./contracts.js";
import { requestDraft, reviewDraft } from "./draft.js";
import { reviewApproved, validateDraft } from "./validate.js";
const iso=(d:Date)=>d.toISOString(); const hash=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");
const safeId=(id:string)=>`explainer-${id.replace(/[^a-z0-9]+/gi,"-").replace(/^-|-$/g,"").toLowerCase()}`;
const recent=(s:ExplainerSource,now:Date)=>{const value=s.eventDate!=="unknown"?s.eventDate:s.publishedAt;return value!=="unknown"&&now.getTime()-Date.parse(value)>=0&&now.getTime()-Date.parse(value)<=30*86400000};
export async function buildProgressExplainers(input:{sources:ExplainerSource[];now:Date;previous?:ProgressExplainersArtifact;model?:ExplainerModel;upstreamConstrained?:boolean}):Promise<{artifact:ProgressExplainersArtifact;report:ExplainerRunReport}>{
  const report:ExplainerRunReport={requestsSucceeded:0,structureRejected:0,evidenceRejected:0,semanticRejected:0,timedOut:0,failed:0,retained:0,removed:0}; const now=iso(input.now);
  const current=new Map(input.sources.map(s=>[s.canonicalId,s])); const retained=(input.previous?.cards??[]).filter(c=>current.get(c.canonicalId)?.revision===c.sourceRevision).map(c=>({...c,checkedAt:now,historical:!recent(current.get(c.canonicalId)!,input.now)})); report.retained=retained.length; report.removed=(input.previous?.cards.length??0)-retained.length;
  const retainedIds=new Set(retained.map(c=>c.canonicalId)); const candidates=[...new Map(input.sources.filter(s=>recent(s,input.now)&&!retainedIds.has(s.canonicalId)).map(s=>[s.canonicalId,s])).values()].sort((a,b)=>{const ad=a.materiallyChangedAt!=="unknown"?Date.parse(a.materiallyChangedAt):Date.parse(a.eventDate!=="unknown"?a.eventDate:a.publishedAt);const bd=b.materiallyChangedAt!=="unknown"?Date.parse(b.materiallyChangedAt):Date.parse(b.eventDate!=="unknown"?b.eventDate:b.publishedAt);return bd-ad||a.canonicalId.localeCompare(b.canonicalId)}).slice(0,3);
  const created:ProgressExplainerCard[]=[]; let circuit=false;
  for(const source of candidates){if(!input.model||circuit){report.failed++;continue}try{const raw=await requestDraft(input.model,source);report.requestsSucceeded++;const checked=validateDraft(raw,source);if(!checked.ok){report[checked.kind==="structure"?"structureRejected":"evidenceRejected"]++;continue}const review=await reviewDraft(input.model,source,checked.draft);report.requestsSucceeded++;if(!reviewApproved(review,checked.draft)){report.semanticRejected++;continue}const base={...checked.draft,id:safeId(source.canonicalId),canonicalId:source.canonicalId,sourceRevision:source.revision,kind:source.kind,evidence:source.evidence,eventDate:source.eventDate,publishedAt:source.publishedAt,materiallyChangedAt:source.materiallyChangedAt,checkedAt:now,historical:false};created.push({...base,revision:hash(base)});}catch(error){if(error instanceof Error&&/timeout/i.test(error.message))report.timedOut++;else report.failed++;circuit=true;}}
  const cards=[...created,...retained].sort((a,b)=>{const sa=current.get(a.canonicalId)!,sb=current.get(b.canonicalId)!;const av=sa.materiallyChangedAt!=="unknown"?Date.parse(sa.materiallyChangedAt):0,bv=sb.materiallyChangedAt!=="unknown"?Date.parse(sb.materiallyChangedAt):0;return bv-av||a.canonicalId.localeCompare(b.canonicalId)});
  const changed=created.length>0||report.removed>0; const unavailable=!cards.length&&(!input.sources.length||report.failed>0); let status:ProgressExplainersArtifact["status"]=changed&&cards.length?"updated":input.upstreamConstrained||report.failed>0?"constrained":unavailable?"unavailable":"no-new-content";if(status==="constrained"&&!cards.length)status="unavailable";
  return {artifact:{schemaVersion:1,generatedAt:now,lastContentUpdatedAt:changed?now:(input.previous?.lastContentUpdatedAt??null),checkedAt:now,status,cards},report};
}
